### ISSUE TITLE
A few minor problems

### ISSUE THREAD

**Issue by EmilyLiu543** [CHEN-XDU/GMSS#1]
1. Hello, could you please tell me what your data shape is after data preprocessing? 

![image](https://user-images.githubusercontent.com/94903117/174927508-d40dac93-42ba-4037-bf7d-42424ac1b0d2.png)

2. Why is the division of brain regions in the code inconsistent with table 1? Why do you divide it like that？
![image](https://user-images.githubusercontent.com/94903117/174927254-064d81ba-5786-4e6b-a6df-304b8e9233e7.png)

Looking forward to your reply. Thank you！

**Comment by JShan1001** [comment]
Could you tell me how you preprocessed the original SEED file into npy format? and could you please tell me what your data shape is after data preprocessing? Looking forward to your reply. Thank you！

**Comment by haojiubujian91** [comment]
I have the same problem as you
Looking forward to the author's reply

**Comment by 11cjxcjxcjxcjx** [comment]
I have the same problem as you
Looking forward to the author's reply

**Comment by Imagine-glx** [comment]
代码看的很懵，论文看的也云里雾里，个人感觉可读性很糟糕
1. 从官网下载的数据格式为.mat，但在代码中直接用的是.npy格式
2. 在utils类中可以看到一个生成汉明集的.npy格式的方法，但看不出与.npy格式的数据集输入有什么关系
3. 代码基本没有关键注释

**Comment by shuentang** [comment]
我和你有同样的问题
期待作者的回复

**Comment by biannachen** [comment]
想知道SEED-IV数据集的independent实验，是对于每个section的15个个体进行留一法，即一共进行15*3次试验？还是一个个体包括3个section的sample进行留一法，一共15次试验？期待作者回复，困扰很久了~
